version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: flashcafe-db
    restart: always
    environment:
      POSTGRES_USER: flashcafe
      POSTGRES_PASSWORD: flashcafe123
      POSTGRES_DB: flashcafe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
